### ISSUE TITLE
The location option of launchFlexTemplate is not working

### ISSUE THREAD

**Issue by holyshared** [googleapis/nodejs-dataflow#19] opened 2021-08-22 09:36 UTC
The location option of launchFlexTemplate is not working

I created a dataflow job with **asia-northeast1** as the location of the launchFlexTemplate.
However, the job region becomes **us-central1**.

The code I'm trying is below.

```typescript
import { FlexTemplatesServiceClient } from "@google-cloud/dataflow"

const client = new FlexTemplatesServiceClient({
  projectId: process.env.GCP_PROJECT_ID,
})

client.launchFlexTemplate({
  projectId: process.env.GCP_PROJECT_ID,
  location: process.env.GCP_REGION,
  launchParameter: {
    jobName: "example-job",
    containerSpecGcsPath: process.env.GCP_CONTAINER_SPEC_PATH,
    parameters: {
      input: "gs://bucket/input/input.json",
      output: "gs://bucket/output/output.json",
    },
    environment: {
      subnetwork: process.env.GCP_SUBNETWORK,
      serviceAccountEmail: process.env.GCP_SERVICE_ACCOUNT_EMAIL,
    }
  }
}).then(([res, req]) => {
  console.log("job %s created", res.job.name)
}).catch(err => {
  console.log(err.stack)
})
```

#### Environment details

  - OS: macOS Big Sur 11.4 
  - Node.js version: v14.4.0
  - npm version: 6.14.5
  - `@google-cloud/dataflow` version: 1.0.2

**Comment by meredithslota** [comment] 2021-09-24 23:53
We've identified similar issues in other repos and have escalated this to the API service team since it's not a language-specific library issue. Here are the related issues: 

- https://github.com/googleapis/python-dataflow-client/issues/31: ListJobsRequest is not using the 'location' filter #31
- https://github.com/googleapis/python-dataflow-client/issues/25: Support for locations in the launch_template method #25
- https://github.com/googleapis/nodejs-dataflow/issues/19: The location option of launchFlexTemplate is not working #19
- https://github.com/googleapis/java-dataflow/issues/64: Dataflow: The location field of LaunchFlexTemplateRequest building is not working #64
- https://github.com/googleapis/google-cloud-dotnet/issues/7038: ListJobsAsync() returns only us-central1 jobs #7038 (context from issue is that the `location` parameter isn't working)

Marking this as a P1 bug w/ `external` label.

**Comment by bbhoss** [comment] 2021-11-29 21:07
I couldn't find an existing issue in the Google Issue Tracker so I created one [here](https://issuetracker.google.com/issues/208105329). I suggest starring this issue to anyone else that runs across this problem, hopefully it will get some attention from Google soon.

**Comment by rafaeldl** [comment] 2022-02-02 14:17
I think we solved the problem, now we have to test! [https://github.com/googleapis/nodejs-dataflow/pull/44](link)

**Comment by meredithslota** [comment] 2022-02-08 18:57
This does appear to have been rolled out, at least in the Node.js libraries, in https://github.com/googleapis/nodejs-dataflow/pull/44 — can someone in this thread (@rafaeldl or @bbhoss or @holyshared) confirm if this is working for you now?

**Comment by rafaeldl** [comment] 2022-03-08 14:49
@meredithslota  I'm waiting for the release 1.2.0 #45 . But it lacks some approval for the release. :(

**Comment by meredithslota** [comment] 2022-04-05 21:30
Thanks for flagging that — I requested a review and it looks like it's gone through now. Can you check with the latest version?

**Comment by meredithslota** [comment] 2022-04-11 22:57
@rafaeldl Can you see if the issue is resolved for you with the latest version of the library? It's been released. We're seeing success in other libraries (e.g. this appears fixed in the Python client) just want to validate the Node.js client is working as expected now as well. Thanks!

**Comment by meredithslota** [comment] 2022-04-28 00:12
We are pretty confident that this is nearly fully resolved (another related issue was just fixed: https://github.com/googleapis/gapic-generator-typescript/pull/1133 and should be rolling out shortly) and just needs to make its way into this library. Should happen shortly.

**Closed** 2022-04-28 20:15 UTC
Labels: type: bug, priority: p1, external, api: dataflow
